name: oceantracker
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - alabaster=0.7.12
  - apeye=1.2.0
  - autodocsumm=0.2.9
  - babel=2.9.1
  - beautifulsoup4=4.11.1
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - cachecontrol=0.12.12
  - certifi=2022.9.24
  - cffi=1.15.0
  - cftime=1.5.1.1
  - charset-normalizer=2.0.4
  - colorama=0.4.4
  - cryptography=37.0.1
  - cssutils=2.6.0
  - curl=7.85.0
  - cycler=0.11.0
  - dict2css=0.3.0
  - docutils=0.17.1
  - domdf-python-tools=3.5.0
  - fftw=3.3.9
  - filelock=3.8.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - glib=2.69.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - hdf4=4.2.13
  - hdf5=1.10.6
  - html5lib=1.1
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.3
  - imagesize=1.3.0
  - importlib-metadata=5.0.0
  - importlib-resources=5.10.0
  - importlib_metadata=5.0.0
  - importlib_resources=5.10.0
  - intel-openmp=2021.4.0
  - jinja2=3.0.3
  - jpeg=9e
  - kiwisolver=1.4.2
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=12.0.0
  - libcurl=7.85.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libiconv=1.16
  - libnetcdf=4.6.1
  - libogg=1.3.5
  - libpng=1.6.37
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - llvmlite=0.39.1
  - lockfile=0.12.2
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - msgpack-python=1.0.4
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - natsort=8.2.0
  - netcdf4=1.5.7
  - numba=0.56.3
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openssl=1.1.1q
  - packaging=21.3
  - pcre=8.45
  - pdfrw=0.4
  - pillow=9.2.0
  - pip=22.2.2
  - platformdirs=2.5.2
  - ply=3.11
  - proj=8.2.1
  - psutil=5.9.0
  - pycparser=2.21
  - pygments=2.11.2
  - pyinstrument=3.4.2
  - pyinstrument_cext=0.2.4
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyproj=3.3.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.10.8
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2022.1
  - pyyaml=6.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - reportlab=3.5.68
  - requests=2.27.1
  - rst2pdf=0.98
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - scipy=1.9.3
  - setuptools=65.5.0
  - sip=6.6.2
  - six=1.16.0
  - smartypants=2.0.1
  - snowballstemmer=2.2.0
  - soupsieve=2.3.2.post1
  - sphinx=4.5.0
  - sphinx-autodoc-typehints=1.19.2
  - sphinx-jinja2-compat=0.1.2
  - sphinx-prompt=1.4.0
  - sphinx-tabs=3.3.1
  - sphinx-toolbox=3.1.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlite=3.39.3
  - tabulate=0.9.0
  - tbb=2021.6.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - typing_inspect=0.7.1
  - tzdata=2022f
  - urllib3=1.26.9
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - webencodings=0.5.1
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.10.0
  - zlib=1.2.13
  - zstd=1.5.2
