name: oceantracker
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - matplotlib=3.7.1
  - netcdf4=1.6.0
  - numba=0.56.4
  - numpy=1.23.5
  - pip=23.0.1
  - pyproj=3.4.1
  - python=3.10.10
  - pyyaml=6.0
  - scipy=1.10.0
  - setuptools=65.6.3
  - yaml=0.2.5
  - psutil=5.9.0
  - fiona=1.9.1